# ------------------------------------ #
# -----------m-a-k-e-f-i-l-e---------- #
# ------------------------------------ #

.PHONY: all
all: droga

droga: droga.cpp
	g++ droga.cpp -o droga
	
.PHONY: clean
clean:
	rm -f skladowe