# ------------------------------------ #
# -----------m-a-k-e-f-i-l-e---------- #
# ------------------------------------ #

.PHONY: all
all: skladowe

skladowe: skladowe.cpp
	g++ skladowe.cpp -o skladowe
	
.PHONY: clean
clean:
	rm -f skladowe